x-deploy-config: &default-deploy
  resources:
    reservations:
      cpus: "1"
      memory: 1gb
    limits:
      cpus: "2"
      memory: 2gb

x-networks-config: &default-network
  networks:
    - portainernetwork

name: container-management
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    deploy: *default-deploy
    <<: *default-network

  portainer-agent:
    image: portainer/agent:2.21.5
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /home/heitor/.local/share/docker/:/var/lib/docker:ro
      - /:/host:ro
    deploy: *default-deploy
    <<: *default-network

  minio-bucket-S3:
    restart: always
    image: minio/minio:latest
    container_name: minio_bucket_S3
    volumes:
      - minio_data:/data
    ports:
      - "9005:9000"
      - "9006:9001"
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_password
      - MINIO_ADDRESS=:9000
      - MINIO_PORT=:9000
      - MINIO_STORAGE_USE_HTTPS=False
      - MINIO_CONSOLE_ADDRESS=:9001
    command: server /data
    deploy: *default-deploy
    <<: *default-network

volumes:
  portainer_data:
  minio_data:

networks:
  portainernetwork:
    driver: bridge
    name: homelabnetwork
